# Generated by Django 3.2 on 2022-09-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'processing'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='created', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_given', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product')),
            ],
        ),
    ]
